GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjY0OTJkYmNhNGM0MmRkYmU2YzhiNjM3NyIsImlhdCI6MTY4NzQzMTYyN30.LEZ7gh9TJkEIJk7QjB5LjJQOx2MWiBDcEfRAMbHzKgY

{
  "title": "Gone with the wind",
  "author": "John Doe",
  "url": "https://something",
  "likes": 4
}
###
PUT http://localhost:3003/api/blogs/647f3defdce9b42b165ecb96
Content-Type: application/json

{
  "author": "John Doe",
  "url": "https://something",
  "likes": 7
}
###
DELETE http://localhost:3003/api/blogs/647f3deedce9b42b165ecb94